export enum action {
  ADD = 'ADD',
  ADD_PENDING = 'ADD_PENDING',
  REMOVE_PENDING = 'REMOVE_PENDING',
  CLEAR_PENDING = 'CLEAR_PENDING',
  REMOVE = 'REMOVE',
  CODE = 'CODE'
}

export enum mutation {
  ADD = 'ADD',
  ADD_PENDING = 'ADD_PENDING',
  REMOVE_PENDING = 'REMOVE_PENDING',
  CLEAR_PENDING = 'CLEAR_PENDING',
  REMOVE = 'REMOVE',
  CODE = 'CODE'
}

export enum getter {
  QR = 'QR',
  PENDING = 'PENDING',
  FILTER_PENDING = 'FILTER_PENDING',
  CODE = 'CODE'
}
