name: Create Website Release package

on:
  create:
    tags:
      - v*

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - uses: actions/checkout@v1

      - uses: actions/cache@v2
        with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
            restore-keys: |
              ${{ runner.os }}-gems-
      - name: Install Jekyll
        run: |
          sudo gem install bundler jekyll
          sudo bundle install
          sudo bundle update --bundler
      - name: Build site
        run: bundle exec jekyll build

      - name: Create version.json
        run: 'echo "{ \"version\": \"${{ env.RELEASE_VERSION }}\", \"git_ref\": \"$GITHUB_SHA\"}" > ./_site/version.json'

      - name: Rename folder
        run: mv _site public

      - name: Create tar
        run: tar -czf ct_website_${{ env.RELEASE_VERSION }}.tar.gz ./public

      - name: Upload release tar
        uses: actions/upload-artifact@v1
        with:
            name: ct_website_${{ env.RELEASE_VERSION }}
            path: ct_website_${{ env.RELEASE_VERSION }}.tar.gz
